var textsi;
var textta;

var nVowels;
var consonants= new Array()
var consonantsUni= new Array()
var vowels= new Array()
var vowelsUni= new Array()
var vowelModifiersUni= new Array()
var specialConsonants= new Array()
var specialConsonantsUni= new Array()
var specialCharUni= new Array()
var specialChar= new Array()


vowelsUni[0]='ඌ';    vowels[0]='oo';    vowelModifiersUni[0]='ූ';
vowelsUni[1]='ඕ';    vowels[1]='o\\)';    vowelModifiersUni[1]='ෝ';
vowelsUni[2]='ඕ';    vowels[2]='oe';    vowelModifiersUni[2]='ෝ';
vowelsUni[3]='ආ';    vowels[3]='aa';    vowelModifiersUni[3]='ා';
vowelsUni[4]='ආ';    vowels[4]='a\\)';    vowelModifiersUni[4]='ා';
vowelsUni[5]='ඈ';    vowels[5]='Aa';    vowelModifiersUni[5]='ෑ';
vowelsUni[6]='ඈ';    vowels[6]='A\\)';    vowelModifiersUni[6]='ෑ';
vowelsUni[7]='ඈ';    vowels[7]='ae';    vowelModifiersUni[7]='ෑ';
vowelsUni[8]='ඊ';    vowels[8]='ii';    vowelModifiersUni[8]='ී';
vowelsUni[9]='ඊ';    vowels[9]='i\\)';    vowelModifiersUni[9]='ී';
vowelsUni[10]='ඊ';    vowels[10]='ie';    vowelModifiersUni[10]='ී';
vowelsUni[11]='ඊ';    vowels[11]='ee';    vowelModifiersUni[11]='ී';
vowelsUni[12]='ඒ';    vowels[12]='ea';    vowelModifiersUni[12]='ේ';
vowelsUni[13]='ඒ';    vowels[13]='e\\)';    vowelModifiersUni[13]='ේ';
vowelsUni[14]='ඒ';    vowels[14]='ei';    vowelModifiersUni[14]='ේ';
vowelsUni[15]='ඌ';    vowels[15]='uu';    vowelModifiersUni[15]='ූ';
vowelsUni[16]='ඌ';    vowels[16]='u\\)';    vowelModifiersUni[16]='ූ';
vowelsUni[17]='ඖ';    vowels[17]='au';    vowelModifiersUni[17]='ෞ';
vowelsUni[18]='ඇ';    vowels[18]='/\a';    vowelModifiersUni[18]='ැ';

vowelsUni[19]='අ';    vowels[19]='a';    vowelModifiersUni[19]='';
vowelsUni[20]='ඇ';    vowels[20]='A';    vowelModifiersUni[20]='ැ';
vowelsUni[21]='ඉ';    vowels[21]='i';    vowelModifiersUni[21]='ි';
vowelsUni[22]='එ';    vowels[22]='e';    vowelModifiersUni[22]='ෙ';
vowelsUni[23]='උ';    vowels[23]='u';    vowelModifiersUni[23]='ු';
vowelsUni[24]='ඔ';    vowels[24]='o';    vowelModifiersUni[24]='ො';
vowelsUni[25]='ඓ';    vowels[25]='I';    vowelModifiersUni[25]='ෛ';
nVowels=26;

specialConsonantsUni[0]='ං'; specialConsonants[0]=/\\n/g;
specialConsonantsUni[1]='ඃ'; specialConsonants[1]=/\\h/g;
specialConsonantsUni[2]='ඞ'; specialConsonants[2]=/\\N/g;
specialConsonantsUni[3]='ඍ'; specialConsonants[3]=/\\R/g;
//special characher Repaya
specialConsonantsUni[4]='ර්'+'\u200D'; specialConsonants[4]=/R/g;
specialConsonantsUni[5]='ර්'+'\u200D'; specialConsonants[5]=/\\r/g;

consonantsUni[0]='ඬ'; consonants[0]='nnd';
consonantsUni[1]='ඳ'; consonants[1]='nndh';
consonantsUni[2]='ඟ'; consonants[2]='nng';
consonantsUni[3]='ථ'; consonants[3]='Th';
consonantsUni[4]='ධ'; consonants[4]='Dh';
consonantsUni[5]='ඝ'; consonants[5]='gh';
consonantsUni[6]='ඡ'; consonants[6]='Ch';
consonantsUni[7]='ඵ'; consonants[7]='ph';
consonantsUni[8]='භ'; consonants[8]='bh';
consonantsUni[9]='ශ'; consonants[9]='sh';
consonantsUni[10]='ෂ'; consonants[10]='Sh';
consonantsUni[11]='ඥ'; consonants[11]='GN';
consonantsUni[12]='ඤ'; consonants[12]='KN';
consonantsUni[13]='ළු'; consonants[13]='Lu';
consonantsUni[14]='ද'; consonants[14]='dh';
consonantsUni[15]='ච'; consonants[15]='ch';
consonantsUni[16]='ඛ'; consonants[16]='kh';
consonantsUni[17]='ත'; consonants[17]='th';

consonantsUni[18]='ට'; consonants[18]='t';
consonantsUni[19]='ක'; consonants[19]='k';
consonantsUni[20]='ඩ'; consonants[20]='d';
consonantsUni[21]='න'; consonants[21]='n';
consonantsUni[22]='ප'; consonants[22]='p';
consonantsUni[23]='බ'; consonants[23]='b';
consonantsUni[24]='ම'; consonants[24]='m';
consonantsUni[25]='‍ය'; consonants[25]='\\u005C' + 'y';
consonantsUni[26]='‍ය'; consonants[26]='Y';
consonantsUni[27]='ය'; consonants[27]='y';
consonantsUni[28]='ජ'; consonants[28]='j';
consonantsUni[29]='ල'; consonants[29]='l';
consonantsUni[30]='ව'; consonants[30]='v';
consonantsUni[31]='ව'; consonants[31]='w';
consonantsUni[32]='ස'; consonants[32]='s';
consonantsUni[33]='හ'; consonants[33]='h';
consonantsUni[34]='ණ'; consonants[34]='N';
consonantsUni[35]='ළ'; consonants[35]='L';
consonantsUni[36]='ඛ'; consonants[36]='K';
consonantsUni[37]='ඝ'; consonants[37]='G';
consonantsUni[38]='ඨ'; consonants[38]='T';
consonantsUni[39]='ඪ'; consonants[39]='D';
consonantsUni[40]='ඵ'; consonants[40]='P';
consonantsUni[41]='ඹ'; consonants[41]='B';
consonantsUni[42]='ෆ'; consonants[42]='f';
consonantsUni[43]='ඣ'; consonants[43]='q';
consonantsUni[44]='ග'; consonants[44]='g';
//last because we need to ommit this in dealing with Rakaransha
consonantsUni[45]='ර'; consonants[45]='r';

specialCharUni[0]='ෲ'; specialChar[0]='ruu';
specialCharUni[1]='ෘ'; specialChar[1]='ru';
//specialCharUni[2]='්‍ර'; specialChar[2]='ra';


function sinhalaText() {
    var s,r,v;
    textsi = $('#sitext').val();

    //special consonents
    for (var i=0; i<specialConsonants.length; i++){
        textsi = textsi.replace(specialConsonants[i], specialConsonantsUni[i]);
    }
    //consonents + special Chars
    for (var i=0; i<specialCharUni.length; i++){
        for (var j=0;j<consonants.length;j++){
            s = consonants[j] + specialChar[i];
            v = consonantsUni[j] + specialCharUni[i];
            r = new RegExp(s, "g");
            textsi = textsi.replace(r, v);
        }
    }
    //consonants + Rakaransha + vowel modifiers
    for (var j=0;j<consonants.length;j++){
        for (var i=0;i<vowels.length;i++){
            s = consonants[j] + "r" + vowels[i];
            v = consonantsUni[j] + "්‍ර" + vowelModifiersUni[i];
            r = new RegExp(s, "g");
            textsi = textsi.replace(r, v);
        }
        s = consonants[j] + "r";
        v = consonantsUni[j] + "්‍ර";
        r = new RegExp(s, "g");
        textsi = textsi.replace(r, v);
    }
    //consonents + vowel modifiers
    for (var i=0;i<consonants.length;i++){
        for (var j=0;j<nVowels;j++){
            s = consonants[i]+vowels[j];
            v = consonantsUni[i] + vowelModifiersUni[j];
            r = new RegExp(s, "g");
            textsi = textsi.replace(r, v);
        }
    }

    //consonents + HAL
    for (var i=0; i<consonants.length; i++){
        r = new RegExp(consonants[i], "g");
        textsi = textsi.replace(r, consonantsUni[i]+"්");
    }

    //vowels
    for (var i=0; i<vowels.length; i++){
        r = new RegExp(vowels[i], "g");
        textsi = textsi.replace(r, vowelsUni[i]);
    }

    $('#sitextcon').val(textsi);

}

function tamilText() {
    textta = $('#tatext').val();

    textta= textta.replace(/njau/g, "ஞௌ");
    textta= textta.replace(/njai/g, "ஞை");
    textta = textta.replace(/njee/g, "ஞே");
    textta = textta.replace(/njoo/g, "ஞோ");
    textta = textta.replace(/njaa/g, "ஞா");
    textta = textta.replace(/njuu/g, "ஞூ");
    textta = textta.replace(/njii/g, "ஞீ");
    textta = textta.replace(/nja/g, "ஞ");
    textta = textta.replace(/nji/g, "ஞி");
    textta = textta.replace(/njI/g, "ஞீ");
    textta = textta.replace(/njA/g, "ஞா");
    textta = textta.replace(/nje/g, "ஞெ");
    textta = textta.replace(/njE/g, "ஞே");
    textta = textta.replace(/njo/g, "ஞொ");
    textta = textta.replace(/njO/g, "ஞோ");
    textta = textta.replace(/nju/g, "ஞு");
    textta = textta.replace(/njU/g, "ஞூ");
    textta = textta.replace(/nj/g, "ஞ்");
    textta = textta.replace(/ngau/g, "ஙௌ");
    textta = textta.replace(/ngai/g, "ஙை");
    textta = textta.replace(/ngee/g, "ஙே");
    textta = textta.replace(/ngoo/g, "ஙோ");
    textta = textta.replace(/ngaa/g, "ஙா");
    textta = textta.replace(/nguu/g, "ஙூ");
    textta = textta.replace(/ngii/g, "ஙீ");
    textta = textta.replace(/nga/g, "ங");
    textta = textta.replace(/ngi/g, "ஙி");
    textta = textta.replace(/ngI/g, "ஙீ");
    textta = textta.replace(/ngA/g, "ஙா");
    textta = textta.replace(/nge/g, "ஙெ");
    textta = textta.replace(/ngE/g, "ஙே");
    textta = textta.replace(/ngo/g, "ஙொ");
    textta = textta.replace(/ngO/g, "ஙோ");
    textta = textta.replace(/ngu/g, "ஙு");
    textta = textta.replace(/ngU/g, "ஙூ");
    textta = textta.replace(/ng/g, "ங்");
    textta = textta.replace(/shau/g, "ஷௌ");
    textta = textta.replace(/shai/g, "ஷை");
    textta = textta.replace(/shee/g, "ஷே");
    textta = textta.replace(/shoo/g, "ஷோ");
    textta = textta.replace(/shaa/g, "ஷா");
    textta = textta.replace(/shuu/g, "ஷூ");
    textta = textta.replace(/shii/g, "ஷீ");
    textta = textta.replace(/sha/g, "ஷ");
    textta = textta.replace(/shi/g, "ஷி");
    textta = textta.replace(/shI/g, "ஷீ");
    textta = textta.replace(/shA/g, "ஷா");
    textta = textta.replace(/she/g, "ஷெ");
    textta = textta.replace(/shE/g, "ஷே");
    textta = textta.replace(/sho/g, "ஷொ");
    textta = textta.replace(/shO/g, "ஷோ");
    textta = textta.replace(/shu/g, "ஷு");
    textta = textta.replace(/shU/g, "ஷூ");
    textta = textta.replace(/sh/g, "ஷ்");
    textta = textta.replace(/ nau/g, " நௌ");
    textta = textta.replace(/ nai/g, " நை");
    textta = textta.replace(/ nee/g, " நே");
    textta = textta.replace(/ noo/g, " நோ");
    textta = textta.replace(/ naa/g, " நா");
    textta = textta.replace(/ nuu/g, " நூ");
    textta = textta.replace(/ nii/g, " நீ");
    textta = textta.replace(/ na/g, " ந");
    textta = textta.replace(/ ni/g, " நி");
    textta = textta.replace(/ nI/g, " நீ");
    textta = textta.replace(/ nA/g, " நா");
    textta = textta.replace(/ ne/g, " நெ");
    textta = textta.replace(/ nE/g, " நே");
    textta = textta.replace(/ no/g, " நொ");
    textta = textta.replace(/ nO/g, " நோ");
    textta = textta.replace(/ nu/g, " நு");
    textta = textta.replace(/ nU/g, " நூ");
    textta = textta.replace(/ nth/g, " ந்");
    textta = textta.replace(/-nau/g, "நௌ");
    textta = textta.replace(/-nai/g, "நை");
    textta = textta.replace(/-nee/g, "நே");
    textta = textta.replace(/-noo/g, "நோ");
    textta = textta.replace(/-naa/g, "நா");
    textta = textta.replace(/-nuu/g, "நூ");
    textta = textta.replace(/-nii/g, "நீ");
    textta = textta.replace(/-na/g, "ந");
    textta = textta.replace(/-ni/g, "நி");
    textta = textta.replace(/-nI/g, "நீ");
    textta = textta.replace(/-nA/g, "நா");
    textta = textta.replace(/-ne/g, "நெ");
    textta = textta.replace(/-nE/g, "நே");
    textta = textta.replace(/-no/g, "நொ");
    textta = textta.replace(/-nO/g, "நோ");
    textta = textta.replace(/-nu/g, "நு");
    textta = textta.replace(/-nU/g, "நூ");
    textta = textta.replace(/n-au/g, "நௌ");
    textta = textta.replace(/n-ai/g, "நை");
    textta = textta.replace(/n-ee/g, "நே");
    textta = textta.replace(/n-oo/g, "நோ");
    textta = textta.replace(/n-aa/g, "நா");
    textta = textta.replace(/n-uu/g, "நூ");
    textta = textta.replace(/n-ii/g, "நீ");
    textta = textta.replace(/n-a/g, "ந");
    textta = textta.replace(/n-i/g, "நி");
    textta = textta.replace(/n-I/g, "நீ");
    textta = textta.replace(/n-A/g, "நா");
    textta = textta.replace(/n-e/g, "நெ");
    textta = textta.replace(/n-E/g, "நே");
    textta = textta.replace(/n-o/g, "நொ");
    textta = textta.replace(/n-O/g, "நோ");
    textta = textta.replace(/n-u/g, "நு");
    textta = textta.replace(/n-U/g, "நூ");
    textta = textta.replace(/wau/g, "நௌ");
    textta = textta.replace(/wai/g, "நை");
    textta = textta.replace(/wee/g, "நே");
    textta = textta.replace(/woo/g, "நோ");
    textta = textta.replace(/waa/g, "நா");
    textta = textta.replace(/wuu/g, "நூ");
    textta = textta.replace(/wii/g, "நீ");
    textta = textta.replace(/wa/g, "ந");
    textta = textta.replace(/wi/g, "நி");
    textta = textta.replace(/wI/g, "நீ");
    textta = textta.replace(/wA/g, "நா");
    textta = textta.replace(/we/g, "நெ");
    textta = textta.replace(/wE/g, "நே");
    textta = textta.replace(/wo/g, "நொ");
    textta = textta.replace(/wO/g, "நோ");
    textta = textta.replace(/wu/g, "நு");
    textta = textta.replace(/wU/g, "நூ");
    textta = textta.replace(/ n/g, " ந்");
    textta = textta.replace(/n-/g, "ந்");
    textta = textta.replace(/-n/g, "ந்");
    textta = textta.replace(/w/g, "ந்");
    textta = textta.replace(/nthau/g, "ந்தௌ");
    textta = textta.replace(/nthai/g, "ந்தை");
    textta = textta.replace(/nthee/g, "ந்தே");
    textta = textta.replace(/nthoo/g, "ந்தோ");
    textta = textta.replace(/nthaa/g, "ந்தா");
    textta = textta.replace(/nthuu/g, "ந்தூ");
    textta = textta.replace(/nthii/g, "ந்தீ");
    textta = textta.replace(/ntha/g, "ந்த");
    textta = textta.replace(/nthi/g, "ந்தி");
    textta = textta.replace(/nthI/g, "ந்தீ");
    textta = textta.replace(/nthA/g, "ந்தா");
    textta = textta.replace(/nthe/g, "ந்தெ");
    textta = textta.replace(/nthE/g, "ந்தே");
    textta = textta.replace(/ntho/g, "ந்தொ");
    textta = textta.replace(/nthO/g, "ந்தோ");
    textta = textta.replace(/nthu/g, "ந்து");
    textta = textta.replace(/nthU/g, "ந்தூ");
    textta = textta.replace(/nth/g, "ந்");
    textta = textta.replace(/dhau/g, "தௌ");
    textta = textta.replace(/dhai/g, "தை");
    textta = textta.replace(/dhee/g, "தே");
    textta = textta.replace(/dhoo/g, "தோ");
    textta = textta.replace(/dhaa/g, "தா");
    textta = textta.replace(/dhuu/g, "தூ");
    textta = textta.replace(/dhii/g, "தீ");
    textta = textta.replace(/dha/g, "த");
    textta = textta.replace(/dhi/g, "தி");
    textta = textta.replace(/dhI/g, "தீ");
    textta = textta.replace(/dhA/g, "தா");
    textta = textta.replace(/dhe/g, "தெ");
    textta = textta.replace(/dhE/g, "தே");
    textta = textta.replace(/dho/g, "தொ");
    textta = textta.replace(/dhO/g, "தோ");
    textta = textta.replace(/dhu/g, "து");
    textta = textta.replace(/dhU/g, "தூ");
    textta = textta.replace(/dh/g, "த்");
    textta = textta.replace(/chau/g, "சௌ");
    textta = textta.replace(/chai/g, "சை");
    textta = textta.replace(/chee/g, "சே");
    textta = textta.replace(/choo/g, "சோ");
    textta = textta.replace(/chaa/g, "சா");
    textta = textta.replace(/chuu/g, "சூ");
    textta = textta.replace(/chii/g, "சீ");
    textta = textta.replace(/cha/g, "ச");
    textta = textta.replace(/chi/g, "சி");
    textta = textta.replace(/chI/g, "சீ");
    textta = textta.replace(/chA/g, "சா");
    textta = textta.replace(/che/g, "செ");
    textta = textta.replace(/chE/g, "சே");
    textta = textta.replace(/cho/g, "சொ");
    textta = textta.replace(/chO/g, "சோ");
    textta = textta.replace(/chu/g, "சு");
    textta = textta.replace(/chU/g, "சூ");
    textta = textta.replace(/ch/g, "ச்");
    textta = textta.replace(/zhau/g, "ழௌ");
    textta = textta.replace(/zhai/g, "ழை");
    textta = textta.replace(/zhee/g, "ழே");
    textta = textta.replace(/zhoo/g, "ழோ");
    textta = textta.replace(/zhaa/g, "ழா");
    textta = textta.replace(/zhuu/g, "ழூ");
    textta = textta.replace(/zhii/g, "ழீ");
    textta = textta.replace(/zha/g, "ழ");
    textta = textta.replace(/zhi/g, "ழி");
    textta = textta.replace(/zhI/g, "ழீ");
    textta = textta.replace(/zhA/g, "ழா");
    textta = textta.replace(/zhe/g, "ழெ");
    textta = textta.replace(/zhE/g, "ழே");
    textta = textta.replace(/zho/g, "ழொ");
    textta = textta.replace(/zhO/g, "ழோ");
    textta = textta.replace(/zhu/g, "ழு");
    textta = textta.replace(/zhU/g, "ழூ");
    textta = textta.replace(/zh/g, "ழ்");
    textta = textta.replace(/zau/g, "ழௌ");
    textta = textta.replace(/zai/g, "ழை");
    textta = textta.replace(/zee/g, "ழே");
    textta = textta.replace(/zoo/g, "ழோ");
    textta = textta.replace(/zaa/g, "ழா");
    textta = textta.replace(/zuu/g, "ழூ");
    textta = textta.replace(/zii/g, "ழீ");
    textta = textta.replace(/za/g, "ழ");
    textta = textta.replace(/zi/g, "ழி");
    textta = textta.replace(/zI/g, "ழீ");
    textta = textta.replace(/zA/g, "ழா");
    textta = textta.replace(/ze/g, "ழெ");
    textta = textta.replace(/zE/g, "ழே");
    textta = textta.replace(/zo/g, "ழொ");
    textta = textta.replace(/zO/g, "ழோ");
    textta = textta.replace(/zu/g, "ழு");
    textta = textta.replace(/zU/g, "ழூ");
    textta = textta.replace(/z/g, "ழ்");
    textta = textta.replace(/jau/g, "ஜௌ");
    textta = textta.replace(/jai/g, "ஜை");
    textta = textta.replace(/jee/g, "ஜே");
    textta = textta.replace(/joo/g, "ஜோ");
    textta = textta.replace(/jaa/g, "ஜா");
    textta = textta.replace(/juu/g, "ஜூ");
    textta = textta.replace(/jii/g, "ஜீ");
    textta = textta.replace(/ja/g, "ஜ");
    textta = textta.replace(/ji/g, "ஜி");
    textta = textta.replace(/jI/g, "ஜீ");
    textta = textta.replace(/jA/g, "ஜா");
    textta = textta.replace(/je/g, "ஜெ");
    textta = textta.replace(/jE/g, "ஜே");
    textta = textta.replace(/jo/g, "ஜொ");
    textta = textta.replace(/jO/g, "ஜோ");
    textta = textta.replace(/ju/g, "ஜு");
    textta = textta.replace(/jU/g, "ஜூ");
    textta = textta.replace(/j/g, "ஜ்");
    textta = textta.replace(/thau/g, "தௌ");
    textta = textta.replace(/thai/g, "தை");
    textta = textta.replace(/thee/g, "தே");
    textta = textta.replace(/thoo/g, "தோ");
    textta = textta.replace(/thaa/g, "தா");
    textta = textta.replace(/thuu/g, "தூ");
    textta = textta.replace(/thii/g, "தீ");
    textta = textta.replace(/tha/g, "த");
    textta = textta.replace(/thi/g, "தி");
    textta = textta.replace(/thI/g, "தீ");
    textta = textta.replace(/thA/g, "தா");
    textta = textta.replace(/the/g, "தெ");
    textta = textta.replace(/thE/g, "தே");
    textta = textta.replace(/tho/g, "தொ");
    textta = textta.replace(/thO/g, "தோ");
    textta = textta.replace(/thu/g, "து");
    textta = textta.replace(/thU/g, "தூ");
    textta = textta.replace(/th/g, "த்");
    textta = textta.replace(/-hau/g, "ஹௌ");
    textta = textta.replace(/-hai/g, "ஹை");
    textta = textta.replace(/-hee/g, "ஹே");
    textta = textta.replace(/-hoo/g, "ஹோ");
    textta = textta.replace(/-haa/g, "ஹா");
    textta = textta.replace(/-huu/g, "ஹூ");
    textta = textta.replace(/-hii/g, "ஹீ");
    textta = textta.replace(/-ha/g, "ஹ");
    textta = textta.replace(/-hi/g, "ஹி");
    textta = textta.replace(/-hI/g, "ஹீ");
    textta = textta.replace(/-hA/g, "ஹா");
    textta = textta.replace(/-he/g, "ஹெ");
    textta = textta.replace(/-hE/g, "ஹே");
    textta = textta.replace(/-ho/g, "ஹொ");
    textta = textta.replace(/-hO/g, "ஹோ");
    textta = textta.replace(/-hu/g, "ஹு");
    textta = textta.replace(/-hU/g, "ஹூ");
    textta = textta.replace(/-h/g, "ஹ்");
    textta = textta.replace(/hau/g, "கௌ");
    textta = textta.replace(/hai/g, "கை");
    textta = textta.replace(/hee/g, "கே");
    textta = textta.replace(/hoo/g, "கோ");
    textta = textta.replace(/haa/g, "கா");
    textta = textta.replace(/huu/g, "கூ");
    textta = textta.replace(/hii/g, "கீ");
    textta = textta.replace(/ha/g, "க");
    textta = textta.replace(/hi/g, "கி");
    textta = textta.replace(/hI/g, "கீ");
    textta = textta.replace(/hA/g, "கா");
    textta = textta.replace(/he/g, "கெ");
    textta = textta.replace(/hE/g, "கே");
    textta = textta.replace(/ho/g, "கொ");
    textta = textta.replace(/hO/g, "கோ");
    textta = textta.replace(/hu/g, "கு");
    textta = textta.replace(/hU/g, "கூ");
    textta = textta.replace(/h/g, "க்");
    textta = textta.replace(/kau/g, "கௌ");
    textta = textta.replace(/kai/g, "கை");
    textta = textta.replace(/kee/g, "கே");
    textta = textta.replace(/koo/g, "கோ");
    textta = textta.replace(/kaa/g, "கா");
    textta = textta.replace(/kuu/g, "கூ");
    textta = textta.replace(/kii/g, "கீ");
    textta = textta.replace(/ka/g, "க");
    textta = textta.replace(/ki/g, "கி");
    textta = textta.replace(/kI/g, "கீ");
    textta = textta.replace(/kA/g, "கா");
    textta = textta.replace(/ke/g, "கெ");
    textta = textta.replace(/kE/g, "கே");
    textta = textta.replace(/ko/g, "கொ");
    textta = textta.replace(/kO/g, "கோ");
    textta = textta.replace(/ku/g, "கு");
    textta = textta.replace(/kU/g, "கூ");
    textta = textta.replace(/k/g, "க்");
    textta = textta.replace(/-sau/g, "ஸௌ");
    textta = textta.replace(/-sai/g, "ஸை");
    textta = textta.replace(/-see/g, "ஸே");
    textta = textta.replace(/-soo/g, "ஸோ");
    textta = textta.replace(/-saa/g, "ஸா");
    textta = textta.replace(/-suu/g, "ஸூ");
    textta = textta.replace(/-sii/g, "ஸீ");
    textta = textta.replace(/-sa/g, "ஸ");
    textta = textta.replace(/-si/g, "ஸி");
    textta = textta.replace(/-sI/g, "ஸீ");
    textta = textta.replace(/-sA/g, "ஸா");
    textta = textta.replace(/-se/g, "ஸெ");
    textta = textta.replace(/-sE/g, "ஸே");
    textta = textta.replace(/-so/g, "ஸொ");
    textta = textta.replace(/-sO/g, "ஸோ");
    textta = textta.replace(/-su/g, "ஸு");
    textta = textta.replace(/-sU/g, "ஸூ");
    textta = textta.replace(/-s/g, "ஸ்");
    textta = textta.replace(/Sau/g, "ஸௌ");
    textta = textta.replace(/Sai/g, "ஸை");
    textta = textta.replace(/See/g, "ஸே");
    textta = textta.replace(/Soo/g, "ஸோ");
    textta = textta.replace(/Saa/g, "ஸா");
    textta = textta.replace(/Suu/g, "ஸூ");
    textta = textta.replace(/Sii/g, "ஸீ");
    textta = textta.replace(/Sa/g, "ஸ");
    textta = textta.replace(/Si/g, "ஸி");
    textta = textta.replace(/SI/g, "ஸீ");
    textta = textta.replace(/SA/g, "ஸா");
    textta = textta.replace(/Se/g, "ஸெ");
    textta = textta.replace(/SE/g, "ஸே");
    textta = textta.replace(/So/g, "ஸொ");
    textta = textta.replace(/SO/g, "ஸோ");
    textta = textta.replace(/Su/g, "ஸு");
    textta = textta.replace(/SU/g, "ஸூ");
    textta = textta.replace(/S/g, "ஸ்");
    textta = textta.replace(/rau/g, "ரௌ");
    textta = textta.replace(/rai/g, "ரை");
    textta = textta.replace(/ree/g, "ரே");
    textta = textta.replace(/roo/g, "ரோ");
    textta = textta.replace(/raa/g, "ரா");
    textta = textta.replace(/ruu/g, "ரூ");
    textta = textta.replace(/rii/g, "ரீ");
    textta = textta.replace(/ra/g, "ர");
    textta = textta.replace(/ri/g, "ரி");
    textta = textta.replace(/rI/g, "ரீ");
    textta = textta.replace(/rA/g, "ரா");
    textta = textta.replace(/re/g, "ரெ");
    textta = textta.replace(/rE/g, "ரே");
    textta = textta.replace(/ro/g, "ரொ");
    textta = textta.replace(/rO/g, "ரோ");
    textta = textta.replace(/ru/g, "ரு");
    textta = textta.replace(/rU/g, "ரூ");
    textta = textta.replace(/r/g, "ர்");
    textta = textta.replace(/Rau/g, "றௌ");
    textta = textta.replace(/Rai/g, "றை");
    textta = textta.replace(/Ree/g, "றே");
    textta = textta.replace(/Roo/g, "றோ");
    textta = textta.replace(/Raa/g, "றா");
    textta = textta.replace(/Ruu/g, "றூ");
    textta = textta.replace(/Rii/g, "றீ");
    textta = textta.replace(/Ra/g, "ற");
    textta = textta.replace(/Ri/g, "றி");
    textta = textta.replace(/RI/g, "றீ");
    textta = textta.replace(/RA/g, "றா");
    textta = textta.replace(/Re/g, "றெ");
    textta = textta.replace(/RE/g, "றே");
    textta = textta.replace(/Ro/g, "றொ");
    textta = textta.replace(/RO/g, "றோ");
    textta = textta.replace(/Ru/g, "று");
    textta = textta.replace(/RU/g, "றூ");
    textta = textta.replace(/R/g, "ற்");
    textta = textta.replace(/tau/g, "டௌ");
    textta = textta.replace(/tai/g, "டை");
    textta = textta.replace(/tee/g, "டே");
    textta = textta.replace(/too/g, "டோ");
    textta = textta.replace(/taa/g, "டா");
    textta = textta.replace(/tuu/g, "டூ");
    textta = textta.replace(/tii/g, "டீ");
    textta = textta.replace(/ta/g, "ட");
    textta = textta.replace(/ti/g, "டி");
    textta = textta.replace(/tI/g, "டீ");
    textta = textta.replace(/tA/g, "டா");
    textta = textta.replace(/te/g, "டெ");
    textta = textta.replace(/tE/g, "டே");
    textta = textta.replace(/to/g, "டொ");
    textta = textta.replace(/tO/g, "டோ");
    textta = textta.replace(/tu/g, "டு");
    textta = textta.replace(/tU/g, "டூ");
    textta = textta.replace(/t/g, "ட்");
    textta = textta.replace(/sau/g, "சௌ");
    textta = textta.replace(/sai/g, "சை");
    textta = textta.replace(/see/g, "சே");
    textta = textta.replace(/soo/g, "சோ");
    textta = textta.replace(/saa/g, "சா");
    textta = textta.replace(/suu/g, "சூ");
    textta = textta.replace(/sii/g, "சீ");
    textta = textta.replace(/sa/g, "ச");
    textta = textta.replace(/si/g, "சி");
    textta = textta.replace(/sI/g, "சீ");
    textta = textta.replace(/sA/g, "சா");
    textta = textta.replace(/se/g, "செ");
    textta = textta.replace(/sE/g, "சே");
    textta = textta.replace(/so/g, "சொ");
    textta = textta.replace(/sO/g, "சோ");
    textta = textta.replace(/su/g, "சு");
    textta = textta.replace(/sU/g, "சூ");
    textta = textta.replace(/s/g, "ச்");
    textta = textta.replace(/pau/g, "பௌ");
    textta = textta.replace(/pai/g, "பை");
    textta = textta.replace(/pee/g, "பே");
    textta = textta.replace(/poo/g, "போ");
    textta = textta.replace(/paa/g, "பா");
    textta = textta.replace(/puu/g, "பூ");
    textta = textta.replace(/pii/g, "பீ");
    textta = textta.replace(/pa/g, "ப");
    textta = textta.replace(/pi/g, "பி");
    textta = textta.replace(/pI/g, "பீ");
    textta = textta.replace(/pA/g, "பா");
    textta = textta.replace(/pe/g, "பெ");
    textta = textta.replace(/pE/g, "பே");
    textta = textta.replace(/po/g, "பொ");
    textta = textta.replace(/pO/g, "போ");
    textta = textta.replace(/pu/g, "பு");
    textta = textta.replace(/pU/g, "பூ");
    textta = textta.replace(/p/g, "ப்");
    textta = textta.replace(/bau/g, "பௌ");
    textta = textta.replace(/bai/g, "பை");
    textta = textta.replace(/bee/g, "பே");
    textta = textta.replace(/boo/g, "போ");
    textta = textta.replace(/baa/g, "பா");
    textta = textta.replace(/buu/g, "பூ");
    textta = textta.replace(/bii/g, "பீ");
    textta = textta.replace(/ba/g, "ப");
    textta = textta.replace(/bi/g, "பி");
    textta = textta.replace(/bI/g, "பீ");
    textta = textta.replace(/bA/g, "பா");
    textta = textta.replace(/be/g, "பெ");
    textta = textta.replace(/bE/g, "பே");
    textta = textta.replace(/bo/g, "பொ");
    textta = textta.replace(/bO/g, "போ");
    textta = textta.replace(/bu/g, "பு");
    textta = textta.replace(/bU/g, "பூ");
    textta = textta.replace(/b/g, "ப்");
    textta = textta.replace(/mau/g, "மௌ");
    textta = textta.replace(/mai/g, "மை");
    textta = textta.replace(/mee/g, "மே");
    textta = textta.replace(/moo/g, "மோ");
    textta = textta.replace(/maa/g, "மா");
    textta = textta.replace(/muu/g, "மூ");
    textta = textta.replace(/mii/g, "மீ");
    textta = textta.replace(/ma/g, "ம");
    textta = textta.replace(/mi/g, "மி");
    textta = textta.replace(/mI/g, "மீ");
    textta = textta.replace(/mA/g, "மா");
    textta = textta.replace(/me/g, "மெ");
    textta = textta.replace(/mE/g, "மே");
    textta = textta.replace(/mo/g, "மொ");
    textta = textta.replace(/mO/g, "மோ");
    textta = textta.replace(/mu/g, "மு");
    textta = textta.replace(/mU/g, "மூ");
    textta = textta.replace(/m/g, "ம்");
    textta = textta.replace(/yau/g, "யௌ");
    textta = textta.replace(/yai/g, "யை");
    textta = textta.replace(/yee/g, "யே");
    textta = textta.replace(/yoo/g, "யோ");
    textta = textta.replace(/yaa/g, "யா");
    textta = textta.replace(/yuu/g, "யூ");
    textta = textta.replace(/yii/g, "யீ");
    textta = textta.replace(/ya/g, "ய");
    textta = textta.replace(/yi/g, "யி");
    textta = textta.replace(/yI/g, "யீ");
    textta = textta.replace(/yA/g, "யா");
    textta = textta.replace(/ye/g, "யெ");
    textta = textta.replace(/yE/g, "யே");
    textta = textta.replace(/yo/g, "யொ");
    textta = textta.replace(/yO/g, "யோ");
    textta = textta.replace(/yu/g, "யு");
    textta = textta.replace(/yU/g, "யூ");
    textta = textta.replace(/y/g, "ய்");
    textta = textta.replace(/dau/g, "டௌ");
    textta = textta.replace(/dai/g, "டை");
    textta = textta.replace(/dee/g, "டே");
    textta = textta.replace(/doo/g, "டோ");
    textta = textta.replace(/daa/g, "டா");
    textta = textta.replace(/duu/g, "டூ");
    textta = textta.replace(/dii/g, "டீ");
    textta = textta.replace(/da/g, "ட");
    textta = textta.replace(/di/g, "டி");
    textta = textta.replace(/dI/g, "டீ");
    textta = textta.replace(/dA/g, "டா");
    textta = textta.replace(/de/g, "டெ");
    textta = textta.replace(/dE/g, "டே");
    textta = textta.replace(/do/g, "டொ");
    textta = textta.replace(/dO/g, "டோ");
    textta = textta.replace(/du/g, "டு");
    textta = textta.replace(/dU/g, "டூ");
    textta = textta.replace(/d/g, "ட்");
    textta = textta.replace(/nau/g, "னௌ");
    textta = textta.replace(/nai/g, "னை");
    textta = textta.replace(/nee/g, "னே");
    textta = textta.replace(/noo/g, "னோ");
    textta = textta.replace(/naa/g, "னா");
    textta = textta.replace(/nuu/g, "னூ");
    textta = textta.replace(/nii/g, "னீ");
    textta = textta.replace(/na/g, "ன");
    textta = textta.replace(/ni/g, "னி");
    textta = textta.replace(/nI/g, "னீ");
    textta = textta.replace(/nA/g, "னா");
    textta = textta.replace(/ne/g, "னெ");
    textta = textta.replace(/nE/g, "னே");
    textta = textta.replace(/no/g, "னொ");
    textta = textta.replace(/nO/g, "னோ");
    textta = textta.replace(/nu/g, "னு");
    textta = textta.replace(/nU/g, "னூ");
    textta = textta.replace(/n/g, "ன்");
    textta = textta.replace(/Nau/g, "ணௌ");
    textta = textta.replace(/Nai/g, "ணை");
    textta = textta.replace(/Nee/g, "ணே");
    textta = textta.replace(/Noo/g, "ணோ");
    textta = textta.replace(/Naa/g, "ணா");
    textta = textta.replace(/Nuu/g, "ணூ");
    textta = textta.replace(/Nii/g, "ணீ");
    textta = textta.replace(/Na/g, "ண");
    textta = textta.replace(/Ni/g, "ணி");
    textta = textta.replace(/NI/g, "ணீ");
    textta = textta.replace(/NA/g, "ணா");
    textta = textta.replace(/Ne/g, "ணெ");
    textta = textta.replace(/NE/g, "ணே");
    textta = textta.replace(/No/g, "ணொ");
    textta = textta.replace(/NO/g, "ணோ");
    textta = textta.replace(/Nu/g, "ணு");
    textta = textta.replace(/NU/g, "ணூ");
    textta = textta.replace(/N/g, "ண்");
    textta = textta.replace(/lau/g, "லௌ");
    textta = textta.replace(/lai/g, "லை");
    textta = textta.replace(/lee/g, "லே");
    textta = textta.replace(/loo/g, "லோ");
    textta = textta.replace(/laa/g, "லா");
    textta = textta.replace(/luu/g, "லூ");
    textta = textta.replace(/lii/g, "லீ");
    textta = textta.replace(/la/g, "ல");
    textta = textta.replace(/li/g, "லி");
    textta = textta.replace(/lI/g, "லீ");
    textta = textta.replace(/lA/g, "லா");
    textta = textta.replace(/le/g, "லெ");
    textta = textta.replace(/lE/g, "லே");
    textta = textta.replace(/lo/g, "லொ");
    textta = textta.replace(/lO/g, "லோ");
    textta = textta.replace(/lu/g, "லு");
    textta = textta.replace(/lU/g, "லூ");
    textta = textta.replace(/l/g, "ல்");
    textta = textta.replace(/Lau/g, "ளௌ");
    textta = textta.replace(/Lai/g, "ளை");
    textta = textta.replace(/Lee/g, "ளே");
    textta = textta.replace(/Loo/g, "ளோ");
    textta = textta.replace(/Laa/g, "ளா");
    textta = textta.replace(/Luu/g, "ளூ");
    textta = textta.replace(/Lii/g, "ளீ");
    textta = textta.replace(/La/g, "ள");
    textta = textta.replace(/Li/g, "ளி");
    textta = textta.replace(/LI/g, "ளீ");
    textta = textta.replace(/LA/g, "ளா");
    textta = textta.replace(/Le/g, "ளெ");
    textta = textta.replace(/LE/g, "ளே");
    textta = textta.replace(/Lo/g, "ளொ");
    textta = textta.replace(/LO/g, "ளோ");
    textta = textta.replace(/Lu/g, "ளு");
    textta = textta.replace(/LU/g, "ளூ");
    textta = textta.replace(/L/g, "ள்");
    textta = textta.replace(/vau/g, "வௌ");
    textta = textta.replace(/vai/g, "வை");
    textta = textta.replace(/vee/g, "வே");
    textta = textta.replace(/voo/g, "வோ");
    textta = textta.replace(/vaa/g, "வா");
    textta = textta.replace(/vuu/g, "வூ");
    textta = textta.replace(/vii/g, "வீ");
    textta = textta.replace(/va/g, "வ");
    textta = textta.replace(/vi/g, "வி");
    textta = textta.replace(/vI/g, "வீ");
    textta = textta.replace(/vA/g, "வா");
    textta = textta.replace(/ve/g, "வெ");
    textta = textta.replace(/vE/g, "வே");
    textta = textta.replace(/vo/g, "வொ");
    textta = textta.replace(/vO/g, "வோ");
    textta = textta.replace(/vu/g, "வு");
    textta = textta.replace(/vU/g, "வூ");
    textta = textta.replace(/v/g, "வ்");
    textta = textta.replace(/gau/g, "கௌ");
    textta = textta.replace(/gai/g, "கை");
    textta = textta.replace(/gee/g, "கே");
    textta = textta.replace(/goo/g, "கோ");
    textta = textta.replace(/gaa/g, "கா");
    textta = textta.replace(/guu/g, "கூ");
    textta = textta.replace(/gii/g, "கீ");
    textta = textta.replace(/ga/g, "க");
    textta = textta.replace(/gi/g, "கி");
    textta = textta.replace(/gI/g, "கீ");
    textta = textta.replace(/gA/g, "கா");
    textta = textta.replace(/ge/g, "கெ");
    textta = textta.replace(/gE/g, "கே");
    textta = textta.replace(/go/g, "கொ");
    textta = textta.replace(/gO/g, "கோ");
    textta = textta.replace(/gu/g, "கு");
    textta = textta.replace(/gU/g, "கூ");
    textta = textta.replace(/g/g, "க்");
    textta = textta.replace(/au/g, "ஔ");
    textta = textta.replace(/ai/g, "ஐ");
    textta = textta.replace(/aa/g, "ஆ");
    textta = textta.replace(/ee/g, "ஏ");
    textta = textta.replace(/ii/g, "ஈ");
    textta = textta.replace(/uu/g, "ஊ");
    textta = textta.replace(/oo/g, "ஓ");
    textta = textta.replace(/-1000/g, "௲");
    textta = textta.replace(/-100/g, "௱");
    textta = textta.replace(/-10/g, "௰");
    textta = textta.replace(/-1/g, "௧");
    textta = textta.replace(/-2/g, "௨");
    textta = textta.replace(/-3/g, "௩");
    textta = textta.replace(/-4/g, "௪");
    textta = textta.replace(/-5/g, "௫");
    textta = textta.replace(/-6/g, "௬");
    textta = textta.replace(/-7/g, "௭");
    textta = textta.replace(/-8/g, "௮");
    textta = textta.replace(/-9/g, "௯");
    textta = textta.replace(/i/g, "இ");
    textta = textta.replace(/I/g, "ஈ");
    textta = textta.replace(/a/g, "அ");
    textta = textta.replace(/A/g, "ஆ");
    textta = textta.replace(/e/g, "எ");
    textta = textta.replace(/E/g, "ஏ");
    textta = textta.replace(/i/g, "இ");
    textta = textta.replace(/I/g, "ஈ");
    textta = textta.replace(/u/g, "உ");
    textta = textta.replace(/U/g, "ஊ");
    textta = textta.replace(/o/g, "ஒ");
    textta = textta.replace(/O/g, "ஓ");
    textta = textta.replace(/x/g, "௯");
    textta = textta.replace(/q/g, "ஃ");

    $('#tatextcon').val(textta);
}
